### ISSUE TITLE
JOSS review: installation

### ISSUE THREAD

**Issue by znicholls** [JGCRI/stitches#76]
At the moment, the installation instructions are only for installation from source. It would be great to add the ability to install from pip (and conda if you're feeling ambitious) as it is the standard packaging solution for Python.

https://github.com/openjournals/joss-reviews/issues/5525

**Comment by Zeitsperre** [comment]
I looked into this in my review and unfortunately, the `STITCHES` name is taken on PyPI, (so it might be worthwhile to rename this project?). Having the project pip-installable would also help in self-enforcing packaging/metadata standards-compliance, in addition to other added benefits like discoverability. 

Inclusion of `stitches in conda-forge would be fantastic for many climate research applications, but perhaps further down-the-line. I would gladly offer a hand in that once the project is in a more production-ready state.

**Comment by crvernon** [comment]
Yes, it is unfortunate that the stitches name has already been taken on PyPI.  And also we are currently unable to change the name due to some organizational constraints.  However, we will definitely consider the conda-forge option as I agree this would be great to add.  

I am going to close this issue for now but will add this do our development log.  And thank you @Zeitsperre for the willingness to lend a hand!  We will take you up on that!

**Comment by znicholls** [comment]
One other thought on this: for the pyam package, the pyam name was already taken on PyPI so it is on PyPI as pyam-iamc instead. Perhaps this could be put on PyPI as stitches-jgcri or something?
